ARG ELK_VERSION

# https://www.docker.elastic.co/
# ${ELK_VERSION}
FROM docker.elastic.co/logstash/logstash:latest

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json